"""Bash tab-completion, generated from the live argument parser.

`eval "$(authorlm completion)"` in ~/.bash_profile registers completion for
subcommands, per-command actions (e.g. `concept tri<TAB>`), option flags,
option values with declared choices (e.g. `--kind hist<TAB>`), and
manuscript names after -m/--manuscript. Generated by introspecting
build_parser(), so it stays in sync with the CLI automatically.

Compatible with the stock macOS bash 3.2.
"""

from __future__ import annotations

import argparse


def _sub_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction:
    return next(
        action for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    )


# (command, action) → the id/name list a bare positional should complete
# with (served by the hidden `authorlm _ids <kind>` helper).
DYNAMIC_POSITIONALS: dict[str, dict[str, str]] = {
    "intent": {"complete": "intents", "abandon": "intents", "retire": "intents"},
    "belief": {"answer": "beliefs"},
    "concept": {"retire": "concepts", "edit": "concepts", "show": "concepts",
                "confirm": "confirmables", "unconfirm": "edges",
                "reject-edge": "edges"},
    "doc": {"retire": "docs", "revive": "docs-retired",
            "push": "docs", "pull": "docs", "open": "docs"},
    "proposal": {"accept": "proposals", "dismiss": "proposals"},
    "unregister": {},  # name completes with manuscripts (special-cased below)
}

# Commands whose FIRST positional (no action word) completes dynamically.
SIMPLE_POSITIONALS: dict[str, str] = {"extract": "docs"}


def collect_words():
    """Introspect the parser once for every completer (bash and shell).
    Returns (commands, command_words, value_choices) where value_choices
    maps option → list of values (None means 'complete directories')."""
    from .cli import build_parser

    parser = build_parser()
    sub = _sub_action(parser)
    commands = [c.dest for c in sub._choices_actions if not c.dest.startswith("_")]

    DIR_DESTS = {"path", "dir", "workspace"}
    command_words: dict[str, list[str]] = {}
    value_choices: dict[str, list[tuple[str, list[str] | None]]] = {}
    for name in commands:
        subparser = sub.choices[name]
        words: list[str] = []
        prev_cases: list[tuple[str, list[str] | None]] = []
        for action in subparser._actions:
            if action.option_strings:
                words.extend(o for o in action.option_strings if o.startswith("--"))
                if action.choices:
                    for opt in action.option_strings:
                        prev_cases.append((opt, sorted(action.choices)))
                elif action.dest in DIR_DESTS:
                    for opt in action.option_strings:
                        prev_cases.append((opt, None))
            elif action.choices:  # positional with declared choices
                words.extend(sorted(action.choices))
        # --all-kind takes the same values as --kind but declares none.
        kind_choices = next((c for o, c in prev_cases if o == "--kind"), None)
        if kind_choices and any(w == "--all-kind" for w in words):
            prev_cases.append(("--all-kind", kind_choices))
        command_words[name] = sorted(set(words) - {"--help"})
        value_choices[name] = prev_cases

    # `help <topic>` completes with the command names themselves.
    command_words["help"] = sorted(set(command_words.get("help", []) + commands))
    return commands, command_words, value_choices


def generate_bash_completion() -> str:
    commands, command_words, value_choices = collect_words()

    case_blocks = []
    for name in commands:
        prev_lines = "".join(
            (
                f'            {opt}) COMPREPLY=( $(compgen -d -- "$cur") ); return;;\n'
                if choices is None else
                f'            {opt}) COMPREPLY=( $(compgen -W "{" ".join(choices)}" -- "$cur") ); return;;\n'
            )
            for opt, choices in value_choices[name]
        )
        prev_case = (
            f'        case "$prev" in\n{prev_lines}        esac\n' if prev_lines else ""
        )
        dynamic = ""
        if name in SIMPLE_POSITIONALS:
            dynamic = (
                '        if [ "$pos1" = "yes" ]; then\n'
                f'            _authorlm_ids {SIMPLE_POSITIONALS[name]}\n'
                '            [ ${#COMPREPLY[@]} -gt 0 ] && return\n'
                '        fi\n'
            )
        elif name == "unregister":
            dynamic = (
                '        if [ "$pos1" = "yes" ]; then\n'
                '            COMPREPLY=( $(compgen -W "$(authorlm _manuscripts 2>/dev/null)" -- "$cur") )\n'
                '            [ ${#COMPREPLY[@]} -gt 0 ] && return\n'
                '        fi\n'
            )
        elif DYNAMIC_POSITIONALS.get(name):
            act_lines = "".join(
                f'                {action}) _authorlm_ids {kind};;\n'
                for action, kind in DYNAMIC_POSITIONALS[name].items()
            )
            dynamic = (
                '        if [ "$pos2" = "yes" ]; then\n'
                '            case "$act" in\n'
                f'{act_lines}'
                '            esac\n'
                '            [ ${#COMPREPLY[@]} -gt 0 ] && return\n'
                '        fi\n'
            )
        case_blocks.append(
            f'    {name})\n{prev_case}{dynamic}'
            f'        COMPREPLY=( $(compgen -W "{" ".join(command_words[name])}" -- "$cur") );;\n'
        )

    top = " ".join(commands)
    return f'''_authorlm_ids() {{
    local IFS=$'\\n'
    COMPREPLY=( $(compgen -W "$(authorlm "${{scope[@]}}" _ids "$1" 2>/dev/null)" -- "$cur") )
}}
_authorlm_complete() {{
    local cur prev cmd word i j act pos1 pos2
    local scope=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    # Carry any -m/-w on the line into helper queries.
    j=1
    while [ $j -lt $COMP_CWORD ]; do
        case "${{COMP_WORDS[$j]}}" in
            -m|--manuscript) scope=("${{scope[@]}}" -m "${{COMP_WORDS[$((j+1))]}}"); j=$((j+2));;
            -w|--workspace) scope=("${{scope[@]}}" -w "${{COMP_WORDS[$((j+1))]}}"); j=$((j+2));;
            *) j=$((j+1));;
        esac
    done
    if [ "$prev" = "-m" ] || [ "$prev" = "--manuscript" ]; then
        COMPREPLY=( $(compgen -W "$(authorlm _manuscripts 2>/dev/null)" -- "$cur") )
        return
    fi
    if [ "$prev" = "-w" ] || [ "$prev" = "--workspace" ]; then
        COMPREPLY=( $(compgen -d -- "$cur") )
        return
    fi
    cmd=""
    i=1
    while [ $i -lt $COMP_CWORD ]; do
        word="${{COMP_WORDS[$i]}}"
        case "$word" in
            -m|--manuscript|-w|--workspace) i=$((i+2));;
            -*) i=$((i+1));;
            *) cmd="$word"; break;;
        esac
    done
    if [ -z "$cmd" ]; then
        COMPREPLY=( $(compgen -W "{top} -m --manuscript -w --workspace" -- "$cur") )
        return
    fi
    act="${{COMP_WORDS[$((i+1))]:-}}"
    pos1=no; pos2=no
    if [[ "$cur" != -* && "$prev" != --* ]]; then
        [ $COMP_CWORD -gt $i ] && pos1=yes
        [ $COMP_CWORD -gt $((i+1)) ] && pos2=yes
    fi
    case "$cmd" in
{"".join(case_blocks)}    esac
}}
complete -o filenames -F _authorlm_complete authorlm
'''
