"""The reader-load manifest — a DERIVED report, refreshed on every push.

A manuscript-root SIDECAR alongside `pronunciations.md`: markdown,
Doc-mirrored as an ordinary tab, and excluded from the reading order, from
concept scanning, from summaries and from every export by the same
`structure.is_sidecar` flag.

It answers one question, per essay and across the book: **what does this
essay assume that no earlier essay ever supplied?** For essay N that is
`ASSUMES(N)` minus everything essays 1..N-1 `INTRODUCED` — set arithmetic
over the stored summaries, normalized against the concept graph's names and
aliases so that "The Dharma", "Dharma" and an alias of either collapse to
one concept.

**It is DERIVED, and it is never a source of truth.** Nothing reads it back;
`refresh` recomputes it from scratch and overwrites whatever was there, so an
edit made in the Doc tab survives exactly until the next push. The file says
so in its own first line, because a generated file that does not announce
itself is a file someone will eventually edit in good faith.

**It never blocks anything.** The summaries it reads can be missing, stale,
deprecated or upstream-stale; every one of those is rendered with the `!!`
marker `write status` uses and the row is still shown. A report that refuses
to appear when the book is mid-flight is a report that is never there when it
is wanted.

The known limitation, stated because the numbers look more exact than they
are: `ASSUMES` and `INTRODUCES` are prose lists written by the summarizer,
not a controlled vocabulary, so a fraction of every debt column is sentence
fragments rather than concepts. Normalizing against the graph fixes the alias
half of that and cannot fix the fragment half. The real repair is upstream,
in the summarizer prompt.
"""

from __future__ import annotations

import re
from pathlib import Path

from .db import Database, loads

FILENAME = "manifest.md"

# The summary's own section labels (summaries.summarizer_prompt).
_ASSUMES = "ASSUMES"
_INTRODUCES = "INTRODUCES"

_HEADER = (
    "<!-- GENERATED by 'authorlm doc push'. Edits here are discarded on the "
    "next push. -->\n"
)


def _canonical_names(db: Database, manuscript_id: str) -> dict[str, str]:
    """Every graph name and alias, lowercased, to its concept's own name."""
    out: dict[str, str] = {}
    for row in db.all(
            "SELECT name, aliases FROM concept_nodes WHERE manuscript_id = ? "
            "AND status != 'retired'", (manuscript_id,)):
        for name in [row["name"], *loads(row["aliases"], [])]:
            if name and name.strip():
                out[name.strip().lower()] = row["name"]
    return out


def _normalize(term: str, canon: dict[str, str]) -> str | None:
    t = re.sub(r"[*`_]", "", term).strip().strip(".").strip()
    t = re.sub(r"^(the|a|an)\s+", "", t, flags=re.I)
    if len(t) < 3:
        return None
    return canon.get(t.lower(), t)


def _field(summary: str, key: str, canon: dict[str, str]) -> list[str]:
    """One labelled list out of a summary, normalized against the graph."""
    m = re.search(rf"^{key}:(.*?)(?=^[A-Z ]+:|\Z)", summary or "",
                  re.S | re.M)
    if not m:
        return []
    body = m.group(1).strip()
    if body.lower().startswith("none"):
        return []
    out = []
    for part in re.split(r"[;,]| and ", body):
        term = _normalize(part, canon)
        if term:
            out.append(term)
    return out


def compute(db: Database, manuscript: dict) -> list[dict]:
    """One row per essay in reading order, each with its unmet debt.

    A term counts as SUPPLIED once an earlier essay has either introduced it
    or leaned on it: the second time a reader meets a word is not the moment
    they first lacked it. So the debt column is FIRST unmet appearance, not
    standing debt, and it is the shape of an on-ramp rather than a tally of
    sins.
    """
    from . import summaries as sums

    canon = _canonical_names(db, manuscript["id"])
    root = Path(manuscript["path"])
    # `status` carries the reading order and each summary's freshness;
    # `all_summaries` carries the text. Two calls rather than one because
    # freshness is the thing this report must not hide, and `status` is the
    # single place the whole system decides it.
    stored = sums.all_summaries(db, manuscript["id"])
    order = sums.status(db, manuscript)

    rows, supplied = [], set()
    for entry in order:
        row = stored.get(entry["file"]) or {}
        summary = row.get("summary") or ""
        introduces = set(_field(summary, _INTRODUCES, canon))
        assumes = set(_field(summary, _ASSUMES, canon))
        debt = sorted(assumes - supplied)
        path = root / entry["file"]
        try:
            words = len(path.read_text(encoding="utf-8").split())
        except OSError:
            words = 0
        rows.append({"file": entry["file"], "words": words,
                     "introduces": len(introduces), "debt": debt,
                     "state": entry.get("state") or "missing"})
        supplied |= introduces | assumes
    return rows


def render(rows: list[dict]) -> str:
    """The report, as the markdown that becomes the Doc tab."""
    if not rows:
        return (_HEADER + "\n# Reader load\n\nNo essay summaries on record "
                "yet. Run 'authorlm summarize rebuild'.\n")
    worst = max((len(r["debt"]) for r in rows), default=0) or 1
    total = sum(r["words"] for r in rows)
    stale = [r["file"] for r in rows if r["state"] != "fresh"]

    out = [_HEADER, "\n# Reader load\n",
           f"{len(rows)} units, {total:,} words. For each essay: what it "
           "assumes that no earlier essay supplied.\n"]
    if stale:
        out.append(
            f"**{len(stale)} of {len(rows)} summaries are not fresh**, and "
            "their rows are marked. A marked row describes the essay as it "
            "was when its summary was last built, not as it stands now — "
            "`authorlm summarize rebuild` clears this.\n")
    out.append("| essay | words | introduces | debt | curve | |")
    out.append("|---|---:|---:|---:|---|---|")
    for r in rows:
        bar = "█" * round(len(r["debt"]) / worst * 20)
        mark = "" if r["state"] == "fresh" else f"!! {r['state']}"
        out.append(f"| {r['file']} | {r['words']} | {r['introduces']} | "
                   f"{len(r['debt'])} | {bar} | {mark} |")

    out.append("\n## The debts\n")
    out.append("Assumed by the essay, introduced by no essay before it. "
               "Some entries are sentence fragments rather than concepts — "
               "the summaries' lists are prose, not a controlled "
               "vocabulary.\n")
    any_debt = False
    for r in rows:
        if r["debt"]:
            any_debt = True
            mark = "" if r["state"] == "fresh" else f" *(!! {r['state']})*"
            out.append(f"- **{r['file']}**{mark} — " + ", ".join(r["debt"]))
    if not any_debt:
        out.append("- None. Every essay stands on ground an earlier one laid.")
    return "\n".join(out) + "\n"


def refresh(db: Database, manuscript: dict) -> tuple[Path, list[dict]]:
    """Recompute and overwrite the sidecar. Returns the path and the rows."""
    rows = compute(db, manuscript)
    path = Path(manuscript["path"]) / FILENAME
    path.write_text(render(rows), encoding="utf-8")
    return path, rows
